name: flutter_ebook_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  material_design_icons_flutter:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/burger.jpg
    - images/cheesechilly.jpg
    - images/noodles.jpg
    - images/pizza.jpg
    - images/hawkers.jpg
    - images/bluehill.jpg
    - images/pizzahut.jpg
    - images/flipping.jpg
    - assets/data.json

  fonts:
    - family: Samantha
      fonts:
        - asset: fonts/Samantha.ttf
